### ISSUE TITLE
Sometimes the chart doesn't fit the parent element's size

### ISSUE THREAD

**Issue by denislins** [pablojim/highcharts-ng#300] opened 2015-04-02 19:34 UTC
I'm having a problem adding a chart into a fluid div. It doesn't fit the size of the chart's parent div, and it overflows it instead, like this:

![image](https://cloud.githubusercontent.com/assets/832802/6971741/09bf1788-d955-11e4-93a8-5eea226aebe3.png)

If I keep refreshing the page, eventually it will work, showing the chart correctly:

![image](https://cloud.githubusercontent.com/assets/832802/6971776/533f4144-d955-11e4-90a1-22513b711fd0.png)

I later discovered that if I resized the browser, the chart will then be displayed correctly, regardless of the resolution I choose, so the problem only occurs on the first load. Another test I did was to remove the chartConfig object, passing an empty object instead, but it didn't help as well.

I'm using bootrstrap, with a markup similar to this:

```
<div class="col-md-7">
  <highchart class="chart" config="ctrl.chartConfig"></highchart>
</div>
```

Also, I'm using latest Angular, Highstock (with standalone adapter) and Highcharts-ng. I tried switching to Highcharts, but no help.

Could this be a bug?

**Comment by denislins** [comment] 2015-04-02 19:43
I managed to fix this by broadcasting the reflow event. But despite this fact, I think this could be handled automatically by the library. Calling an event this way seemed a little hacky to me. What do you think?

**Comment by iven** [comment] 2015-04-08 09:00
Same as #211?

**Comment by waazes** [comment] 2015-04-08 15:59
I tried this #211 but it didnt work.

**Comment by manfredk** [comment] 2015-04-20 18:46
I've got the same problem with charts within a bootstrap container initially sized to full window width. 

Initially: 
![image](https://cloud.githubusercontent.com/assets/3963984/7237757/e479b076-e79d-11e4-866e-e43ada81c938.png)

After window resizing:
![image](https://cloud.githubusercontent.com/assets/3963984/7237774/ff55031e-e79d-11e4-8a9f-134c7c174e69.png)

Broadcasting the reflow event as suggested in #211 didn't work, either. Probably the container's computed width is not yet set when the chart is rendered or it's not transferred correctly. 

@pablojim Barry, any sustainable solution to this problem?

**Comment by pablojim** [comment] 2015-04-21 10:27
Could you make a fiddle?

**Comment by manfredk** [comment] 2015-04-21 11:23
Sure, i'll notify you when  ready

**Comment by manfredk** [comment] 2015-04-22 15:41
@pablojim Plunkr demonstrating the issue is ready under http://plnkr.co/edit/OJWhXyUIeyNnYD0qdq0A

**Comment by pablojim** [comment] 2015-04-22 16:31
Not a complete fix but... http://plnkr.co/edit/PwkHRJtsMXlxG9UMXJol?p=preview

See: http://stackoverflow.com/questions/17301572/angularjs-evalasync-vs-timeout and http://stackoverflow.com/questions/17225106/anyway-to-trigger-a-method-when-angular-is-done-adding-scope-updates-to-the-dom/17239084#17239084

So maybe we need a callback from the directive to execute after the DOM changes are made?

Pull requests accepted!

**Comment by manfredk** [comment] 2015-04-22 17:59
Great, that worked. Actually, I tried that before, but didn't realize that I would have to inject the dependency for $timeout (didn't look twice and thought it's a plain Javascript timeout).

Thx a lot for your prompt reply and the fix.

**Closed** 2015-04-23 10:10 UTC

**Comment by pablojim** [comment] 2015-04-23 10:11
No problem. Could you add an entry to the faq in the main readme?

**Comment by manfredk** [comment] 2015-04-23 11:06
Done

**Comment by waazes** [comment] 2015-04-26 14:10
I'm using $ionicSideMenuDelegate (Ionic framework) and by resizing the window, the chart width is not correct. I made a codepen: http://codepen.io/anon/pen/OVPRrx

How to fix that?

**Comment by patelshiv** [comment] 2015-07-13 14:28
I was using old version of this but when i updated with new version it solved some of my issues but now    i am not able to see border around series name. anyone have idea how to fix that.
thanks

**Comment by SushantKadam008** [comment] 2015-08-28 11:39
HI,
I had a smiliar issue but providing bootstrap class to higchart tag solved the issue.

**Comment by mendaomn** [comment] 2015-09-14 09:46
Hello everybody,
I'm using the reflow fix but this causes the initial series' animation to be skipped or stopped, how can I have it working after reflowing?

**Comment by sadlerw** [comment] 2015-10-05 13:40
Should we open a new issue for the above question about how to get the initial animation back?  I'd like to know the answer too.

**Comment by romain10009** [comment] 2015-12-01 06:39
i'm using ng-if, and when the ng-if goes true to show the chart, it gets displayed with a wrong size, i need to resize window to make it behave as intended. It would be nice to have that handled somehow...

**Comment by florisb** [comment] 2015-12-14 14:57
I have fixed this by making the chart data available a bit after the page is loaded. This way the containers get setup first. Then the chart is loaded, this way the proper size is already available to highCharts and everything works as expected (including animations)

    $timeout(function() {
        $scope.dashboardData = dashboardData;
    }, 100);

In my template i simple use `<highchart config="dashboardData" ng-if="dashboardData"></highchart>` to prevent loading the highcharts element before data is available.

**Comment by bumblebeen** [comment] 2016-02-18 06:31
This did the trick for me instead of using $timeout. I guess it all depends on when you display and render your data
```
 func: function (chart) {
     $scope.$evalAsync(function () {
            chart.reflow();
       });
  }
```

**Comment by SushantKadam008** [comment] 2016-04-17 20:06
@mendaomn : Even I am facing the same issue. Initially when I use reflow the chart does not animate. For all the subsequent times I can see the animation.

Did you get any solution for this ?

**Comment by gururajmca** [comment] 2016-07-07 13:17
As florisb mentioned the solution worked me... thanks guys..

**Comment by dilani-maheswaran** [comment] 2016-07-27 07:39
Is there any option I can use to stop the chart from redrawing when I update the chart? In my case, I want to dynamically update the title of chart when exporting. The whole chart gets redrawn every time i change the chart title.

**Comment by pablojim** [comment] 2017-03-02 21:04
see #564
