### ISSUE TITLE
Chart not re sizing to bootstrap fluid column

### ISSUE THREAD

**Issue by Bclayson** [pablojim/highcharts-ng#374] opened 2015-09-03 22:37 UTC
I just updated all my packages and my charts are now not automatically sizing to their bootstrap fluid columns. I've seen several other issues posted for this but either 1. They are old and no longer valid, 2. they work poorly, 3. They remove the loading animations of highcharts, which I don't want to sacrifice. What is a solution? Is this something we can figure out long term?

**Comment by seadour** [comment] 2015-09-04 00:19
Can you please share an example on jsfiddle or similar service, so we can try to troubleshoot your specific problem?

**Comment by mdedetrich** [comment] 2015-09-07 09:54
@seadour I think this may be a duplicate of https://github.com/pablojim/highcharts-ng/issues/211. I am currently having a look at the issue in my fork

**Comment by pablojim** [comment] 2015-09-09 21:14
@mdedetrich I'm grateful for your thoughts...

**Comment by mdedetrich** [comment] 2015-09-09 23:57
@pablojim I have a solution which is working, it currently defers the loading of the main highcharts after a `$(window).resize()` event. The only issue is regarding flicker.

I am currently also thinking it should be an option in the directive of the highcharts when it gets initialized

**Comment by pablojim** [comment] 2015-09-12 17:22
@mdedetrich - There seem to be two main avenues to fix this behaviour at the moment:

- delaying rendering somehow/or redrawing after some pause
- Setting a fixed size on the chart/the chart's div

I'm not sure if there is another preferable approach.

**Comment by mdedetrich** [comment] 2015-09-14 04:55
@pablojim 
The idea of the pull request that I am working on at the moment is to make the charts work with variable width's (usually used in responsive frameworks such as bootstrap or foundation), so the solution I am going for is delayed initialization. I am just trying to figure out how to simulate something like ng-cloak to prevent the flickering

**Comment by seadour** [comment] 2015-09-14 05:02
If you use the `defer` attribute on your script tags for the highcharts/highcharts-ng libraries so that they load after the Bootstrap/Foundation CSS files, does it help?

e.g.

    <script src="js/highcharts.js" defer>

Also, does this also happen with vanilla Highcharts/Bootstrap or just the highcharts-ng directive in Angular?

**Comment by mtholdefer** [comment] 2015-09-16 16:34
@seadour I am having the same issue with vanilla Highcharts/Bootstrap, so it exists on both.

**Comment by Bclayson** [comment] 2015-09-16 17:02
The width sizing issue was eliminated when I stopped using an
ng-show/ng-hide over the chart until results via ajax were returned, OR if
I replaced it with an ng-if. Don't ask me why that's the case. The height
issue still remained when using the ng-if, but I just fixed that by
dynamically creating the height based on the number of results I got back
from the ajax request.

On Wed, Sep 16, 2015 at 10:34 AM, Matthew Holdefer <notifications@github.com
> wrote:

> @seadour <https://github.com/seadour> I am having the same issue with
> vanilla Highcharts/Bootstrap, so it exists on both.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pablojim/highcharts-ng/issues/374#issuecomment-140796286>
> .
>



-- 
Bob Clayson
Cell 801.427.8322
Linkedin
<http://t.sidekickopen20.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbKGxW63Bmsl7d-dXCVdDPP256dw-zf4lDXsn02?t=https%3A%2F%2Fwww.linkedin.com%2Fprofile%2Fview%3Fid%3D315070030%26trk%3Dnav_responsive_tab_profile&si=5869050673496064&pi=8e46fe28-9308-4674-e404-589719e049be>

**Comment by seadour** [comment] 2015-09-16 17:38
If the issue is happening in plain Highcharts/Bootstrap without highcharts-ng, I would argue that it's not in the purview of highcharts-ng and we should close this issue and open a new one in the Highcharts repository (or search for a related issue).

@Bclayson, it sounds to me like Angular is making modifications to DOM elements after Highcharts has measured them. So Highcharts thinks the container is a certain width/height and draws the chart to fit, but then Angular modifies the container's width/height afterward with ng-show/ng-hide.

I think there's probably an elegant way in Angular to postpone Highcharts operations until after the DOM has completely finished rendering but I'm not really sure what the best way would be.

**Closed** 2017-01-27 21:08 UTC
Labels: close_as_pre_v1_0_0
