### ISSUE TITLE
TypeError: Cannot read property 'xAxis' of undefined

### ISSUE THREAD

**Issue by tobiashoeft** [pablojim/highcharts-ng#475] opened 2016-05-10 05:23 UTC
`angular.js:13424 TypeError: Cannot read property 'xAxis' of undefined
    at Object.<anonymous> (http://code.highcharts.com/stock/highstock.js:391:67)
    at O (http://code.highcharts.com/stock/highstock.js:28:357)
    at Object.Ba.redraw (http://code.highcharts.com/stock/highstock.js:217:401)
    at Object.<anonymous> (http://code.highcharts.com/stock/highstock.js:396:350)
    at Object.a.(anonymous function) [as redraw] (http://code.highcharts.com/stock/highstock.js:22:321)
    at http://localhost:1446/Scripts/highcharts-ng.js:384:35
    at m.$digest (http://localhost:1446/Scripts/angular.min.js:140:306)
    at m.$apply (http://localhost:1446/Scripts/angular.min.js:143:249)
    at g (http://localhost:1446/Scripts/angular.min.js:95:444)
    at x (http://localhost:1446/Scripts/angular.min.js:100:50)(anonymous function) @ angular.js:13424(anonymous function) @ angular.js:10137m.$digest @ angular.js:16887m.$apply @ angular.js:17133g @ angular.js:11454x @ angular.js:11652v.onload @ angular.js:11593XMLHttpRequest.send (async)(anonymous function) @ angular.js:11630n @ angular.js:11423g @ angular.js:11133(anonymous function) @ angular.js:15757m.$eval @ angular.js:17025m.$digest @ angular.js:16841m.$apply @ angular.js:17133(anonymous function) @ angular.js:1713invoke @ angular.js:4625c @ angular.js:1711yc @ angular.js:1731de @ angular.js:1616(anonymous function) @ angular.js:30709i @ jquery-2.2.0.min.js:2j.fireWith @ jquery-2.2.0.min.js:2n.extend.ready @ jquery-2.2.0.min.js:2J @ jquery-2.2.0.min.js:2`

i have the following problem

here my chartconfig : 

`        $scope.chartConfig = {

            options: {

                scrollbar: {
                    enabled: true
                },
                subtitle: {
                    text: ""
                },
                chart: {
                    height: 600,
                    zoomType: "x",
                    resetZoomButton: {
                        position: {
                            x: 5,
                            y: 20
                        }
                    }
                },
                navigator: {
                    enabled: true
                },
                rangeSelector: {
                    enabled: true,
                    inputEnabled: $("#chart").width() > 480,
                    buttons: [
                        {
                            type: "minute",
                            count: 60,
                            text: "1h"
                        }, {
                            type: "minute",
                            count: 360,
                            text: "6h"
                        }, {
                            type: "minute",
                            count: 720,
                            text: "12h"
                        }, {
                            type: "day",
                            count: 1,
                            text: "1d"
                        }, {
                            type: "month",
                            count: 1,
                            text: "1m"
                        },
                        {
                            type: "year",
                            count: 1,
                            text: "1y"
                        }, {
                            type: "all",
                            text: "All"
                        }
                    ],
                    selected: 3
                },
                plotOptions: {
                    series: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        point: {
                            events: {
                                click: function (e) {
                                    $scope.openSelectedPointModal();
                                },
                                select: function (e) {

                                    var sensorId = this.series.options.id;

                                    GetValueByTimestampAndId.getValue(Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x), sensorId)
                                                               .success(function (value2) {
                                                                   $scope.selectedpoint.value = value2;
                                                                   $scope.selectedpoint.bid = sensorId;
                                                               })
                                                               .error(function (error) {
                                                                   console.log(error);
                                                                   $scope.protokoll.push("Serie kann nicht aus Datenbank geholt werden: " + error.MessageDetail);
                                                                   $scope.loading3 = false;
                                                               }).finally(function () {
                                                                   $scope.loading3 = false;
                                                               });

                                    $scope.selectedpoint.station = this.series.name;
                                    $scope.selectedpoint.timestamp = Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x);

                                }

                            }
                        },
                        dataGrouping: {
                            enabled: false
                        }
                    }

                },

                xAxis: [
                    {

                        type: "datetime",
                        events: {
                            afterSetExtremes: function (e) {
                                var min = Highcharts.dateFormat('%d.%m.%Y %H:%M', e.min);
                                var max = Highcharts.dateFormat('%d.%m.%Y %H:%M', e.max);
                                afterSetExtremes(min, max);
                            }
                        },
                        minRange: 3600000
                      
                    }
                ],
                yAxis: {
                  
                    title: {
                       
                        text:'kumulierte Niederschlagshöhe [mm]'
                    }
                    
                },
                legend: {
                    enabled: true,
                    align: 'center',
                    verticalAlign: 'top',
                    y: 2,
                    floating: true,
                    borderWidth: 0,
                    shadow: true,
                    tooltip:'einblenden/ausblenden'
                },
                title: {
                    style: { "fontSize": "12px" },
                    align: "right",
                    text: "Zeitzone: UTC"
                },
                credits: {
                    enabled: false
                },
                loading: true,
                tooltip: {
                    //formatter: function () {

                    //},
                    valueDecimals: 2,
                    //valueSuffix: 'mm',
                    crosshairs: [
                        {
                            width: 1,
                            dashStyle: "dash",
                            color: "#898989"
                        },
                        {
                            width: 1,
                            dashStyle: "dash",
                            color: "#898989"
                        }
                    ],
                    borderWidth: 1,
                    borderRadius: 5,
                    borderColor: "#a4a4a4",
                    shadow: true,
                    useHTML: true,
                    percentageDecimals: 2,
                    backgroundColor: "rgba(255,255,255,.7)",
                    style: {
                        padding: 0
                    },
                    shared: true
                },
                useHighStocks: true
            },
            series: [],
            func: function (chart) {
                $timeout(function () {
                    chart.reflow();
                }, 0);
            }
        };`

**Comment by mdawood1991** [comment] 2016-05-10 08:45
Having the same issue

**Comment by tobiashoeft** [comment] 2016-05-10 08:55
No solution :( hope anyone know a solution.

I use the /*
 Highstock JS v4.2.5 (2016-05-06)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/

Version :( before it works!

**Comment by mdawood1991** [comment] 2016-05-10 08:56
Okay  I found a solution.

This is happening because of an update in the Highstock/HighChart library on (2016-05-06) - which seems to have broken ng-highcharts

I used an old version (4.2.2) of HighStock.js and it is working now.

http://code.highcharts.com/stock/4.2.2/highstock.js
OR 
http://code.highcharts.com/4.2.2/highcharts.js


Other versions here: http://code.highcharts.com/

**Comment by tobiashoeft** [comment] 2016-05-10 09:39
Thx u mate! Thats gread hope soon we have an pull request how fix that soon.

Thx for reply :-)! :+1:

**Comment by gimebernadet** [comment] 2016-05-19 14:59
I hope the library can fix this issue so we don't have to use an older version of highstock..

**Comment by idangozlan** [comment] 2016-05-23 16:15
+1

**Comment by sanex3339** [comment] 2016-05-31 12:44
+1

**Comment by matyasfodor** [comment] 2016-06-02 12:20
+1

**Comment by leongaban** [comment] 2016-06-02 15:39
@mdawood1991 That was it! We removed `^4.2.3` and changed it to `4.2.2` and that bug went away... breaking change implemented in a patch!

**Comment by jhrabows** [comment] 2016-06-10 15:32
Error happens in redraw
--
            addEvent(chart, 'redraw', function () {
                // Move the scrollbar after redraw, like after data updata even if axes don't redraw
                var scroller = this.scroller,
                    xAxis;
                if (scroller) {
                    xAxis = scroller.baseSeries.xAxis; // scroller is defined but baseSeries is not
                    if (xAxis) {
                        scroller.render(xAxis.min, xAxis.max);
                    }
                }
            });
--
As mentioned above, it was introduced in version 4.2.5. Version 4.2.4 works. This issue has nothing to do with Angular. I am using the plugin directly on my page.

**Comment by jhrabows** [comment] 2016-06-13 20:38
Here is my jsfiddle

http://jsfiddle.net/jhrabows/zwjbk4cd/1/

It blows up when you press a button which calls setExtremes() (which results in a redraw() call)

Note that the issue is with the highstock.js version. Using plain highcharts.js seems to work.

**Comment by jhrabows** [comment] 2016-06-14 15:08
I got a reply from Highstock support. There take is that a declaration of an empty series should include 'data' attribute. In other words, the empty series declaration above should be

series: [{data:[]}],

and not

series: []

**Comment by jhrabows** [comment] 2016-06-15 15:21
Related to https://github.com/highcharts/highcharts/issues/5406

**Comment by pablojim** [comment] 2016-06-29 19:09
Closing as appears not be a highcharts-ng issue.

**Closed by pablojim** 2016-06-29 19:09 UTC
