### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by dpwoodford** [pablojim/highcharts-ng#356] opened 2015-07-30 13:12 UTC
Is there a particular way to include additional highcharts plugins within the directive? For example, I'm trying to add regression lines to a test project of mine at the moment using http://www.highcharts.com/plugin-registry/single/22/Highcharts%20regression.

Adding the regression parameters to the series object appears to have no effect:

<pre>
                     series: [{
                        regression: true,
                        regressionSettings: {
                            type: 'linear',
                            color: 'rgba(223, 83, 83, .9)'
                        },
                        name: 'Moneyball Score',
                        color: 'rgba(223, 83, 83, .5)',
                        data: SeriesA,
                        type: 'scatter'
                    }],
</pre>

The data displays fine, but no line is added. Testing similar outside of the directive seems to function OK.  Any advice is welcome; if it's not currently supported I'll push it to a feature request..

Thanks.

**Comment by pablojim** [comment] 2015-07-30 14:02
It should work as far as I'm aware. Could you make a jsfiddle?

**Comment by dpwoodford** [comment] 2015-07-31 04:06
Sure, here's a quick mockup:

http://jsfiddle.net/25vu94zw/

**Comment by pablojim** [comment] 2015-07-31 10:00
Thanks. The reason it doesn't work is that the highcharts-ng plugin maintains a list of series. The regression plugin adds another series that the highcharts-ng plugin is unaware of so it is not displayed.

This could be fixed by maintaining a better two way binding between the chart's series and highcharts-ng's config object. I'm not sure if the appropriate events exist in highcharts for this. The regression plugin could probably be modifed to work with highcharts-ng also.

**Closed** 2015-09-03 18:26 UTC

**Comment by maddy25** [comment] 2016-07-23 22:59
Is there a solution yet?

**Comment by maddy25** [comment] 2016-07-24 04:45
Commenting out following from the highcharts-ng worked for me.
//Now remove any missing series
            for(var i = chart.series.length - 1; i >= 0; i--) {
                var s = chart.series[i];
                /*if (ids.indexOf(s.options.id) < 0) {
                    s.remove(false);
                }*/
            };

**Comment by Kesymaru** [comment] 2017-02-03 07:57
I have exactly the same issue with the same plugin, i think changing the highcharts-ng code is not a good solution.

I would like to know if someone else knows another solution for this problem?
